version: "3.0"

services:
    borgclient:
        container_name: borgclient
        image: valmati/borgclient
        hostname: client
        environment:
          - TZ=Europe/Madrid
          - BORG_SERVER=borgserver
          - PREFIX=ClientPrefix
          - SOURCE=/home /otherPath
          - BOT_TOKEN=123:ABC
          - CHAT_ID=-123
          - PASSPHRASE=passphrase
          - KEEP_HOURLY=4
          - KEEP_DAILY=7
          - KEEP_WEEKLY=4
          - KEEP_MONTHLY=6
        volumes:
          - ./ssh_keys:/root/.ssh
          - ./log/:/log
          - ./config:/borgconfig
        restart: unless-stopped